---
collections:
  - name: 'community.windows'
    version: '>=2.3.0'
  - name: 'ansible.windows'
    version: '>=2.7.0'
  - name: 'pichincha.sre'
    version: '>=1.0.1'
    source: 'https://192.168.64.9/pulp_ansible/galaxy/published/'
