---
# - name: Install pichincha.sre collection from a repo.
#   ansible.builtin.command: ansible-galaxy collection install git+https://github.com/phenomenone/pichincha.sre.git,main
#   register: result
- name: Example clone of a single branch
  ansible.builtin.git:
    repo: 'https://github.com/phenomenone/pichincha.sre.git'
    dest: /tmp/checkout
    single_branch: yes
    version: main

- name: Install pichincha.sre collection from a repo.
  ansible.builtin.command: ansible-galaxy collection build
  args:
    chdir: /tmp/checkout/
  register: resultbuild

- name: Install pichincha.sre collection from a repo.
  ansible.builtin.command: ansible-galaxy collection publish -c - vvvv pichincha-sre-1.0.7tar.gz
  args:
    chdir: /tmp/checkout/
  register: resultpublish

- name: Check installed collections
  ansible.builtin.command: ansible-galaxy collection list
  register: resultlist

- name: Check if pichincha.sre is installed
  ansible.builtin.assert:
    that:
      - "'pichincha.sre' in result.stdout"
    fail_msg: "The collection pichincha.sre is not installed."
    success_msg: "The collection pichincha.sre is installed."