- name: Check installed collections
  ansible.builtin.command: ansible-galaxy collection list
  register: result
  delegate_to: localhost

- name: Display installed collections
  ansible.builtin.debug:
    var: result.stdout_lines
  delegate_to: localhost

- name: Check if pichincha.sre is installed
  ansible.builtin.assert:
    that:
      - "'pichincha.sre' in result.stdout"
    fail_msg: "The collection pichincha.sre is not installed."
    success_msg: "The collection pichincha.sre is installed."
  delegate_to: localhost

- name: import role
  ansible.builtin.include_role:
    name: pichincha.sre.wintel_readiness
  vars:
    win_app_pools:
      - New-apppool-test
      - New-apppool-test-2
    win_services:
      - New-service-test
      - New-service-test-2
    url_monitoreo:
      - https://example.com
